# We parse variable convert nested servers to a list
- name: Generate nodes info
  set_fact:
    nodes: "{{ servers.values() }}"

- include_tasks: single-server.yaml
  vars:
    servername: "{{ item.keys()[0]}}"
    baremetal_node: "{{ 'random' if item.values()[0] == None else item.values()[0] }}"
  with_items: "{{ nodes }}"
