# The default_gateway for node.
default_gateway: '10.168.2.254'

# The vips for openstack used.
# Format:
# ---
# vips:
#   network: ip
#

vips:
  - external: 10.168.2.200
  - internal: 10.168.1.200

