# This variable defined the role, servername and baremetal node mapping.
# In 'servers' dict contain roles dicts, each role dict contain list of servername
# and baremetal node dict. When baremeatl value is empty will random choose a
# baremetal node to deploy.
#
# Avaliable value for this variable:
#   - role: controller, compute (string)
#   - servername: normal string (string)
#   - baremetal node: baremetal node or uuid, if empty will use random baremetal node.
# Format:
# ---
# servers:
#   role:
#     - servernameA: baremetal_nodeA
#     - servernameB:
#
# Example:
# Controller 1 assign to baremetal1, Controller2,3 use random baremetal node,
# Compute node use baremetal node  5d0ec6af-e300-4d0b-9098-4bb2f0300486
# ---
# servers:
#   controller:
#     - control1: baremetal1
#     - control2:
#     - control3:
#   compute:
#     - compute1: 5d0ec6af-e300-4d0b-9098-4bb2f0300486

servers:
  controller:
    - sosctl01: 10.168.61.8
    - sosctl02: 10.168.61.9
    - sosctl03: 10.168.61.10
  compute:
    - scp201: 10.168.61.1
    - scp202: 10.168.61.2
    - scp203: 10.168.61.3
    - scp204: 10.168.61.4
    - sgv101: 10.168.61.5
    - sgv102: 10.168.61.6
    - sgt401: 10.168.61.7
  network:
    - sedg01: 10.168.61.11
    - sedg02: 10.168.61.12

# This variable defined the network required for each role.
# Acourding the list create the port named with `servername-network-port`
#
# Avaliable value for this variable:
#   role: controller, compute, network
#   network: internal, external, storage, compute, octavia, tunnel
#
# Format:
# ---
# role_used_network:
#   role: [ network, network, network ]
#
# Example:
# Controller with 1 node c1, compute with 1 node com1.
# Controller with internal, external networks. Compute with internal, network.
# ---
# role_used_network:
#   controller: [ internal, external, storage ]
#   compute: [ internal, tunnel, storage ]
#
# Then create port:
#   - c1-internal-port
#   - c1-external-port
#   - com1-internal-port
#

role_used_network:
  controller: [ internal, external, storage, octavia ]
  compute: [ internal, tunnel, storage, octavia ]
  network: [ internal, tunnel, octavia, external ]

# This variable defined the network for deploy nodes.
# In 'networks' dict conatain each network info with nested dicts.
#
# Avaliable for this variable:
#   - network: tunnel, internal, external, storage, ctlplane(required), octavia
#   - vlan_id: vlan id for that network
#   - cidr: network's CIDR (required)
#   - hosts: a list of { servername: ip} , defined the server need this ip, if not assign ip in here will random generate.
#
# Format:
# ---
# networks:
#   network:
#     cidr: 192.168.10.0/24
#     vlan_id: 1002
#     hosts:
#       n1: 1.2.3.4
#       n2: 2.3.4.5
#

networks:
  tunnel:
    vlan_id: 1003
    cidr: 10.168.3.0/24
    hosts:
      scp201: 10.168.3.1
      scp202: 10.168.3.2
      scp203: 10.168.3.3
      scp204: 10.168.3.4
      sgv101: 10.168.3.5
      sgv102: 10.168.3.6
      sgt401: 10.168.3.7
      sedg01: 10.168.3.8
      sedg02: 10.168.3.9

  internal:
    vlan_id: 1001
    cidr: 10.168.1.0/24
    hosts:
      scp201: 10.168.1.1
      scp202: 10.168.1.2
      scp203: 10.168.1.3
      scp204: 10.168.1.4
      sgv101: 10.168.1.5
      sgv102: 10.168.1.6
      sgt401: 10.168.1.7
      sosctl01: 10.168.1.8
      sosctl02: 10.168.1.9
      sosctl03: 10.168.1.10
      sedg01: 10.168.1.11
      sedg02: 10.168.1.12

  external:
    vlan_id: 1002
    cidr: 10.168.2.0/24
    hosts:
      sosctl01: 10.168.2.1
      sosctl02: 10.168.2.2
      sosctl03: 10.168.2.3
      sedg01: 10.168.2.4
      sedg02: 10.168.2.5

  octavia:
    vlan_id: 1005
    cidr: 10.168.5.0/24
    hosts:
      scp201: 10.168.5.1
      scp202: 10.168.5.2
      scp203: 10.168.5.3
      scp204: 10.168.5.4
      sgv101: 10.168.5.5
      sgv102: 10.168.5.6
      sgt401: 10.168.5.7
      sosctl01: 10.168.5.8
      sosctl02: 10.168.5.9
      sosctl03: 10.168.5.10
      sedg01: 10.168.5.11
      sedg02: 10.168.5.12

  storage:
    vlan_id: 1023
    cidr: 10.168.23/24
    hosts:
      scp201: 10.168.23.1
      scp202: 10.168.23.2
      scp203: 10.168.23.3
      scp204: 10.168.23.4
      sgv101: 10.168.23.5
      sgv102: 10.168.23.6
      sgt401: 10.168.23.7
      sosctl01: 10.168.23.8
      sosctl02: 10.168.23.9
      sosctl03: 10.168.23.10

  ctlplane:
    cidr: 10.168.60/24
    hosts:
      scp201: 10.168.60.1
      scp202: 10.168.60.2
      scp203: 10.168.60.3
      scp204: 10.168.60.4
      sgv101: 10.168.60.5
      sgv102: 10.168.60.6
      sgt401: 10.168.60.7
      sosctl01: 10.168.60.8
      sosctl02: 10.168.60.9
      sosctl03: 10.168.60.10
      sedg01: 10.168.60.11
      sedg02: 10.168.60.12

# The default_gateway for node.
default_gateway: '10.168.2.254'

# The vips for openstack used.
# Format:
# ---
# vips:
#   network: ip
#

vips:
  - external: 10.168.2.200
  - internal: 10.168.1.200

