#!/bin/bash

function find_base {
    if test -f "$PWD/ansible/site.yaml"; then
        PLAYBOOK=$PWD/ansible/site.yaml
    elif test -f "$HOME/ansible-kolla-os/ansible/site.yaml"; then
        PLAYBOOK=$HOME/ansible-kolla-os/ansible/site.yaml
    else
        echo "Playbook not found!"
        exit 1
    fi
}
function process_cmd {
    echo "$ACTION: $CMD"
    $CMD
    if [[ $? -ne 0 ]]; then
        echo "Command failed $CMD"
        exit 1
    fi
}

function usage {
    cat <<EOF
Usage: $0 COMMAND [--options]

Options:
    --config, -c        Config file path, default is config.yaml
    --help, -h          Show this usage information
    --wait              Wait server deploy complete
    --verbose, -v       Increase verbosity of ansible-playbook
    --inventory, -i     Specify path to ansible inventory file
    --hosts             Specify hosts or group use comma split string to run plays required --inventory
    --nodes-csv         Nodes csv file path, default is nodes.csv
    --networks-csv      Networks csv file path, default is networks.csv
    --update-etc-hosts  Update /etc/hosts, add alias for ssh, use this option with create-server.


Commands:
    full-create-server      Create network and deploy servers
    create-server           Deploy all server defined.
    deployed                Create nic-config and inventory from csv directly
    generate-inventory      Generate inventory file.

    update-network-config   Update network, port and nic config without apply, use --inventory and --hosts for specific node or group.
    update-nic-config       Update all nic config without apply, use --inventory and --hosts for specific node or group.
    apply-nic-config        Apply nic-config to deployed ndoe
    update-etc-hosts        Update /etc/hosts, add alias for ssh.
    destroy                 Destroy Servers, Port, Network, Configs.
EOF
}
SHORT_OPTS="hi:c:v"
LONG_OPTS="help,wait,verbose,inventory:,hosts:,config:,nodes-csv:,networks-csv:,update-etc-hosts"

RAW_ARGS="$*"
ARGS=$(getopt -o "${SHORT_OPTS}" -l "${LONG_OPTS}" --name "$0" -- "$@") || { usage >&2; exit 2; }

eval set -- "$ARGS"
INVNTORY_REQUIRED=false
VERBOSITY=
INVENTORY=
HOSTS=
EXTRA_OPTS=${EXTRA_OPTS}
find_base

while [ "$#" -gt 0 ]; do
    case "$1" in
        (--config|-c)
            if test -f "$2";then
                EXTRA_OPTS="$EXTRA_OPTS -e config_path=$2"
            else
                echo "Config file $2 not found!"
                exit 3
            fi
            shift 2
            ;;
        (--hosts)
            HOSTS="-e host=$2"
            INVNTORY_REQUIRED=true
            shift 2
            ;;
        (--inventory|-i)
            INVENTORY="--inventory $2"
            shift 2
            ;;
        (--wait)
            EXTRA_OPTS="$EXTRA_OPTS -e wait_deploy=yes"
            shift
            ;;
        (--verbose|-v)
            VERBOSITY="$VERBOSITY --verbose"
            shift
            ;;
        (--update-etc-hosts)
            EXTRA_OPTS="$EXTRA_OPTS --tags etc-hosts"
            shift
            ;;
        (--nodes-csv)
            EXTRA_OPTS="$EXTRA_OPTS -e nodes_csv_path=$2"
            shift 2
            ;;
        (--networks-csv)
            EXTRA_OPTS="$EXTRA_OPTS -e networks_csv_path=$2"
            shift 2
            ;;
        (--help|-h)
            usage
            shift
            exit 0
            ;;
        (--)
            shift
            break
            ;;
        (*)
            echo 'error'
            exit 3
            ;;
esac
done

if [ "$INVNTORY_REQUIRED" = "true" ];then
    if [ "x$INVENTORY" = "x" ];then
        echo "ERROR: When use --hosts required --inventory."
        exit 3
    fi
fi

case "$1" in
    (deployed)
        ACTION="Deploy with deployed servers."
        EXTRA_OPTS="$EXTRA_OPTS --tags deployed-server "
        ;;
    (destroy)
        ACTION="Destroy all Servers, Port, Netowrk"
        EXTRA_OPTS="$EXTRA_OPTS --tags destroy -e deploy_action=destroy"
        ;;
    (full-create-server)
        ACTION="Create network, port, server"
        EXTRA_OPTS="$EXTRA_OPTS --tags full-create-server -e deploy_action=create"
        ;;
    (update-network-config)
        ACTION="Update network port and nic config"
        if [ "x$INVENTORY" = "x" ];then
            INVENTORY='-i kolla-os-inventory.yaml'
        fi
        if [ "x$HOSTS" = "x" ];then
            HOSTS="-e host=all"
        fi
        EXTRA_OPTS="$EXTRA_OPTS --tags update-network-config -e deploy_action=reconfig"
        ;;
    (create-server)
        ACTION="Deploy all defined servers not update inventory"
        EXTRA_OPTS="$EXTRA_OPTS --tags create-server -e deploy_action=create"
        ;;
    (generate-inventory)
        ACTION="Generate invntory"
        EXTRA_OPTS="$EXTRA_OPTS --tags create-inventory -e deploy_action=create"
        ;;
    (update-nic-config)
        if [ "x$INVENTORY" = "x" ];then
            INVENTORY='-i kolla-os-inventory.yaml'
        fi
        if [ "x$HOSTS" = "x" ];then
            HOSTS="-e host=all"
        fi
        ACTION="Update nic config only"
        EXTRA_OPTS="$EXTRA_OPTS -e deploy_action=reconfig --tags update-nic-config"
        ;;
    (apply-nic-config)
        if [ "x$INVENTORY" = "x" ];then
            INVENTORY='-i kolla-os-inventory.yaml'
        fi
        if [ "x$HOSTS" = "x" ];then
            HOSTS="-e host=all"
        fi
        ACTION="Apply nic config to nodes"
        EXTRA_OPTS="$EXTRA_OPTS --tags apply-nic-config"
        ;;
    (update-etc-hosts)
        EXTRA_OPTS="--tags etc-hosts"
        ;;
    (*)
        usage
        exit 0
        ;;
esac

CMD="ansible-playbook $INVENTORY $HOSTS $VALIDATE_OPTS $EXTRA_OPTS $PLAYBOOK $VERBOSITY"

process_cmd
