- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: Create require directory
      file:
        state: directory
        dest: /etc/os-net-config
    - name: Copy nic-config
      copy:
        src: "kolla-servers/{{ inventory_hostname }}-config.yaml"
        dest: "/etc/os-net-config/{{ inventory_hostname }}-config.yaml"
    - name: Copy mapping file
      copy:
        src: "kolla-servers/{{ inventory_hostname }}-mapping.yaml"
        dest: "/etc/os-net-config/{{ inventory_hostname }}-mapping.yaml"

    - name: Reconfig network
      shell: |
        os-net-config -c  /etc/os-net-config/{{ inventory_hostname }}-config.yaml \
                      -m /etc/os-net-config/{{ inventory_hostname }}-mapping.yaml
      async: 60
