---
- hosts: "{{ host }}"
  gather_facts: no
  tasks:
    - name: Set vfio module
      lineinfile:
        create: yes
        line: "{{ item }}"
        path: /etc/modules-load.d/vfio.conf
      with_items:
        - "vfio"
        - "vfio_iommu_type1"
        - "vfio_pci"

    - name: Set vfio options
      lineinfile:
        create: yes
        line: "{{ item }}"
        path: /etc/modprobe.d/vfio-options.conf
      with_items:
        - "options vfio-cpi ids=10de:1db6"
    - name: Blacklist modules
      lineinfile:
        create: yes
        line: "{{ item }}"
        path: /etc/modprobe.d/blacklist.conf
      with_items:
        - "blacklist snd_hda_intel"
        - "blacklist amd76x_edac"
        - "blacklist vga16fb"
        - "blacklist rivafb"
        - "blacklist nvidiafb"
        - "blacklist rivatv"
        - "blacklist nvidia"
        - "blacklist nouveau"
        - "options nouveau modeset=0"
    - name: find line
      shell: |
        grep GRUB_CMDLINE_LINUX /etc/default/grub
      register: grub_cmd
    - name: update grub
      lineinfile:
        line: "GRUB_CMDLINE_LINUX=\"{{ grub_cmd.stdout.split('\"')[1] }} intel_iommu=on \""
        regexp: '^GRUB_CMDLINE_LINUX='
        path: /etc/default/grub
    - name: update grub image
      shell: |
        grub2-mkconfig -o /boot/grub2/grub.cfg
        grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
        dracut -f
    - name: Reboot
      shell: |
        reboot
