- hosts: localhost
  gather_facts: no
  tasks:
    - include_vars: 'vars.yaml'
    - debug:
        msg: |
          {{ lookup('pipe','grep ctlplane_port_ip kolla-servers/ctrl1-info.yaml').split(':')[1] }}
    - template:
        src: templates/inventory.j2.yaml
        dest: /tmp/i.yaml
