- name: Get ctlplane info
  shell: |
    source /home/stack/stackrc
    openstack subnet show ctlplane-subnet -c cidr -f value
  register: ctlplane_cidr
  tags:
    - always

- set_fact:
    nic_config_dest: "kolla-servers/{{ servername }}-config.yaml"
    mapping_dest: "kolla-servers/{{ servername }}-mapping.yaml"
  tags:
    - create-server
    - network-create
    - gen-nic-config

- name: "Check {{ role }} mapping file exist"
  find:
    path: "nic-configs/{{ role }}-mapping.yaml"
  register: f
  tags:
    - network-create
    - gen-nic-config

- name: "Generate mapping file for {{ servername }}"
  copy:
    src: "nic-configs/{{ role }}-mapping.yaml"
    dest: "{{ mapping_dest }}"
  when: "f.files | length > 0"
  tags:
    - network-create
    - gen-nic-config

- name: "Generate nic-configs for {{ servername }}"
  copy:
    src: "nic-configs/{{ role }}-config.yaml"
    dest: "{{ nic_config_dest }}"
  tags:
    - network-create
    - gen-nic-config


- name: "Insert ctlplane IP information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'ctlplane$'
    replace: "{{ ctlplane_ip }}/{{ ctlplane_cidr.stdout.split('/')[1] }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Insert storage IP information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'storage$'
    replace: "{{ storage_ip }}/{{ networks.storage.cidr.split('/')[1] }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Insert tunnel IP information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'tunnel$'
    replace: "{{ tunnel_ip }}/{{ networks.tunnel.cidr.split('/')[1] }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Insert ctlplane IP information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'internal$'
    replace: "{{ internal_ip }}/{{ networks.internal.cidr.split('/')[1] }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Insert external IP information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'external$'
    replace: "{{ external_ip }}/{{ networks.external.cidr.split('/')[1] }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Instert external vlan information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'external_vlan_id'
    replace: "{{ networks.external.vlan_id }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Instert internal vlan information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'internal_vlan_id'
    replace: "{{ networks.internal.vlan_id }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Instert storage vlan information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'storage_vlan_id'
    replace: "{{ networks.storage.vlan_id }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Instert tunnel vlan information for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'tunnel_vlan_id'
    replace: "{{ networks.tunnel.vlan_id }}"
  tags:
    - network-create
    - gen-nic-config

- name: "Instert gateway for {{ servername }}"
  replace:
    path: "{{ nic_config_dest }}"
    regexp: 'default_gateway'
    replace: "{{ default_gateway }}"
  tags:
    - network-create
    - gen-nic-config
