- set_fact:
    avaliable_roles: ['controller','compute','network']
  tags:
    - always

- name: Find config in nic-configs
  find:
    paths: "nic-configs"
    patterns: '*-config.yaml'
  register: f
  tags:
    - validate

- name: Validate config filename
  assert:
    that:
      - "{{ item.path.split('/')[-1].split('-')[0] in avaliable_roles }}"
    fail_msg: "{{ item.path.split('/')[-1].split('-')[0] }} nic config use unavaliable role. }}"
  with_items: "{{ f.files }}"
  tags:
    - validate

- name: Find mapping in nic-configs
  find:
    paths: "nic-configs"
    patterns: "*-mapping.yaml"
  register: f
  tags:
    - validate

- name: Validate mapping filename
  assert:
    that:
      - "{{ item.path.split('/')[-1].split('-')[0] in avaliable_roles }}"
    fail_msg: "{{ item.path.split('/')[-1] }} mapping file use unavaliable role. }}"
  with_items: "{{ f.files }}"
  tags:
    - validate

- name: Validate server's role
  assert:
    that:
      - "item in ['controller','compute','network']"
    fail_msg: "{{ item }} is not avaliable role"
  with_items: "{{servers.keys()}}"
  tags:
    - validate

- name: Validate variables are defined
  assert:
    that:
      - "default_gateway is defined"
    fail_msg: "default_gateway variable is not defined"
  tags:
    - validate
