---
# nodes = nodes in roles
# role = controller compute network
# Parse the server's port ips
- name: Prepare node required network info
  set_fact:
    nodes_name: |
      [
        {% for node in nodes %}
        "{{ node.keys()[0] }}",
        {% endfor %}
      ]
    network_require: "['ctlplane'] + {{ role_used_network[role] }}"

# node_use_ip: [
#   {
#     name: c1
#     ctlplane: random
#     internal: 1.2.3.4
#     external: 2.3.4.5
#     storage:
# ]
# network sequence: ctlplane, internal, external, octavia, storage, tunnel
- name: Prepare node required ip info
  set_fact:
    node_use_ip: |
      [
      {% for name in nodes_name %}
        {{ '{' }}
        'name': '{{ name }}',
        {% if networks.ctlplane.hosts is defined %}
        'ctlplane': '{{ networks.ctlplane.hosts[name] | default('random') }}',
        {% else %}
        'ctlplane': 'random',
        {% endif %}
        {% for net in network_require %}
            {% if networks[net].hosts is defined %}
            '{{ net }}': '{{ networks[net].hosts[name] | default('random') }}',
            {% else %}
            '{{ net }}': 'random',
            {% endif %}
        {% endfor %}
      {{ '}' }},
      {% endfor %}
      ]

- include_tasks: "{{ action }}.yaml"
  with_items: "{{ node_use_ip }}"
