- name: "Create {{ servername }} {{ network }} fixed-ip port"
  os_port:
    network: "{{ network }}"
    name: "{{ servername }}-{{ network }}-port"
    fixed_ips:
      - ip_address: "{{ ipaddress }}"
  register: p

- include_tasks: save.yaml
  vars:
    ip: "{{ ipaddress }}"
    id: "{{ p.port.id }}"
