- name: "Generate mapping file"
  copy:
    src: "{{ base_file_path }}/{{ role }}-mapping.yaml"
    dest: "{{ info_file_path }}/{{ nodename }}-mapping.yaml"

- name: "Generate config file"
  copy:
    src: "{{ base_file_path }}/{{ role }}-config.yaml"
    dest: "{{ info_file_path }}/{{ nodename }}-config.yaml"
