- name: Get ctlplane info
  shell: |
    source /home/stack/stackrc
    openstack subnet show ctlplane-subnet -c cidr -f value
  register: ctlplane_cidr

- set_fact:
    nodes_name: |
      [
        {% for role, nodes in servers.items() %}
            {% for node in nodes %}
                '{{ node.keys()[0] }}',
            {% endfor %}
        {% endfor %}
      ]

- include_tasks: copy.yaml
  vars:
    role: "{{ item.key }}"
    nodes: "{{ item.value }}"
  with_dict: "{{ servers }}"

- include_tasks: config.yaml
  vars:
    servername: "{{ item }}"
  with_items: "{{ nodes_name }}"
