---

- name: Create vips
  os_port:
    name: "{{ item.keys()[0] }}_vip"
    network: "{{ item.keys()[0] }}"
    fixed_ips:
      - ip_address: "{{ item.values()[0] }}"
  with_items: "{{ vips }}"
  when:
    - vips is defined
    - use_undercloud

- name: Get node info
  set_fact:
    node_info: "{{ item }}"

- name: Create fixed-ip ports
  include_tasks: static.yaml
  vars:
    network: "{{ item }}"
    servername: "{{ node_info.name }}"
    ipaddress: "{{ node_info[item] }}"
  when:
    - node_info[item] != 'random'
    - use_undercloud
  with_items: "{{ network_require }}"

- name: Create random ip ports
  include_tasks: random.yaml
  vars:
    network: "{{ item }}"
    servername: "{{ node_info.name }}"
  when:
    - node_info[item] == 'random'
    - use_undercloud
  with_items: "{{ network_require }}"

- name: Create ip info
  include_tasks: static.yaml
  vars:
    network: "{{ item }}"
    servername: "{{ node_info.name }}"
    ipaddress: "{{ node_info[item] }}"
  when:
    - not use_undercloud
  with_items: "{{ network_require }}"
