---
- name: Create fixed-ip ports
  include_tasks: static.yaml
  vars:
    network: "{{ item }}"
    servername: "{{ node_info.key }}"
    ipaddress: "{{ node_info.value[item] }}"
  when:
    - node_info[item] != ''
    - use_undercloud
  with_items: "{{ ['ctlplane'] + role_used_network[node_info['role']]}}"
