---
- name: Create fixed-ip ports
  include_tasks: static.yaml
  vars:
    network: "{{ node_network_info }}"
    servername: "{{ name }}"
    ipaddress: "{{ node_info[node_network_info] }}"
  when:
    - node_info[node_network_info] != ''
    - use_undercloud
  with_items: "{{ ['ctlplane'] + role_used_network[node_info.role]}}"
  loop_control:
    loop_var: node_network_info
