---
- name: Get ports
  shell: |
    source /home/stack/stackrc
    openstack port list -f value -c ID -c Status | grep -v ACTIVE | openstack port list -f value -c ID -c Status | grep -v ACTIVE | grep -o '[0-9a-fA-F]\{8\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{12\}' | tr '\n' ' '
  register: delete_ports

- name: Destroy all port
  shell: |
    source /home/stack/stackrc
    openstack port delete {{ delete_ports.stdout }}

- name: "Clean configs"
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ info_file_path }}/*.yaml"
