---

- name: "Destroy all port"
  shell: |
    source /home/stack/stackrc
    openstack port delete $(openstack port list -f value -c ID -c Status | grep -v ACTIVE | awk '{print $1}')

- name: "Clean configs"
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ info_file_path }}/*.yaml"
