---
- name: Create vips
  os_port:
    name: "{{ vip.keys()[0] }}_vip"
    network: "{{ vip.keys()[0] }}"
    fixed_ips:
      - ip_address: "{{ vip.values()[0] }}"
  with_items: "{{ vips }}"
  loop_control:
    loop_var: vip
  when:
    - vips is defined
    - use_undercloud
    - action == 'create'

- include_tasks: "{{ action }}.yaml"
  when: action != 'destroy'

- include_tasks: destroy.yaml
  when: action == 'destroy'
