[all]
{% for node in nodes_csv_list.list %}
{{ node.name }} ansible_host={{ node.ctlplane }} ansible_ssh_user={{ ssh_user }}
{% endfor %}

{% for role in role_used_network.keys() %}

[{{ role  }}]

{% for node in nodes_csv_list.list | selectattr('role','search', role)| list %}
{{ node.name }} ansible_host={{ node.ctlplane }} ansible_ssh_user={{ ssh_user  }}
{% endfor %}

{% endfor%}

