[all]
{% for role, nodes in servers.items() %}
{% for node in nodes %}
{% set cmd= "grep ctlplane {{ info_file_path }}/" + node.keys()[0] + "-info.yaml" %}
{{ node.keys()[0] }} ansible_host={{ lookup('pipe', cmd).split()[2].split(']')[0] }} ansible_ssh_user={{ ssh_user }}
{% endfor %}
{% endfor %}

{% for role, nodes in servers.items() %}

[{{ role  }}]

{% for node in nodes %}
{% set cmd= "grep ctlplane {{ info_file_path  }}/" + node.keys()[0] + "-info.yaml" %}
{{ node.keys()[0]  }} ansible_host={{ lookup('pipe', cmd).split()[2].split(']')[0]  }} ansible_ssh_user={{ ssh_user  }}

{% endfor %}

{% endfor%}
