- name: Set variable
  set_fact:
    role_nic_configs: |
      [
        {% for r in defined_roles %}
            '{{ r }}-config.yaml',
            '{{ r }}-mapping.yaml',
        {% endfor %}
      ]
    fake_data:
      tunnel: '192.168.100.100/24'
      ctlplane: '192.168.99.99/24'
      storage: '192.168.98.98/24'
      external: '192.168.97.97/24'
      internal: '192.168.96.96/24'
      octavia: '192.168.95.95/24'
      tunnel_vlan_id: '1'
      storage_vlan_id: '2'
      external_vlan_id: '3'
      internal_vlan_id: '4'
      octavia_vlan_id: '5'
      default_gateway: '192.168.97.254'

- name: Find defined role nic-configs
  find:
    paths: "{{ nic_config_path }}"
    patterns:
      - "*-config.yaml"
      - "*-mapping.yaml"
  register: nic_config_base

- name: Validate defined role have nic-config files
  assert:
    that: "filedata.path.split('/')[-1] in role_nic_configs"
    fail_msg: "{{ filedata.path.split('/')[-1] }} not a currect config file name"
    success_msg: "All nic config named currected"
  with_items: "{{ nic_config_base.files }}"
  loop_control:
    loop_var: filedata

- tempfile:
    state: directory
  register: tmpdir
- debug: var=tmpdir.path
- name: Generate validate nic-config base
  copy:
    src: "../nic-configs/{{ item }}-config.yaml"
    dest: "{{ tmpdir.path }}/{{ item }}-config.yaml"
  with_items: "{{ defined_roles }}"

- name: Replace validate nic-config
  replace:
    path: "{{ tmpdir.path }}/{{ item[0] }}-config.yaml"
    regexp: "{{ item[1] }}$"
    replace: "{{ fake_data[item[1]] }}"
  with_nested:
    - "{{ defined_roles }}"
    - "{{ fake_data }}"

- name: Test os-net-config with dry_run
  block:
    - shell: |
        os-net-config -c {{ item }} --noop
      register: net_config_dryrun
      failed_when: "net_config_dryrun.stderr_lines | length > 0 or net_config_dryrun.rc != 0"
      with_fileglob: "{{ tmpdir.path }}/*-config.yaml"
  rescue:
    - name: nic-config has wrong syntax
      fail:
        msg: "nic-config has wrong syntax"
  always:
    - file:
        path: "{{ tmpdir.path }}"
        state: absent
        force: yes
