network_config:
  - type: interface
    name: nic2
    onboot: false
    use_dhcp: false

  - type: interface
    name: nic1
    use_dhcp: false
    addresses:
      - ip_netmask: ctlplane

  - type: linux_bond
    name: bond0
    mtu: 8942
    bonding_options: "mode=4"
    use_dhcp: false
    members:
      - type: interface
        name: nic3
      - type: interface
        name: nic4

  - type: vlan
    vlan_id: storage_vlan_id
    device: bond0
    mtu: 8942
    addresses:
      - ip_netmask: storage

  - type: vlan
    vlan_id: external_vlan_id
    device: bond0
    addresses:
      - ip_netmask: external
    mtu: 8942
    routes:
      - default: true
        next_hop: default_gateway

  - type: vlan
    vlan_id: internal_vlan_id
    device: bond0
    mtu: 8942
    addresses:
      - ip_netmask: internal

  - type: vlan
    vlan_id: octavia_vlan_id
    device: bond0
    mtu: 8942
    addresses:
      - ip_netmask: octavia
