---
- name: "Create network"
  os_network:
    name: "{{ name }}"
  when: "name != 'ctlplane'"

- include_tasks: subnet.yaml
  vars:
    network: "{{ name }}"
    cidr: "{{ cidr }}"
  when: "name != 'ctlplane'"
  with_dict: "{{ networks }}"
