---
- name: Read variables
  hosts: localhost
  connection: local
  tags: always
  gather_facts: no
  tasks:
    - include_vars: "{{ config_path | default('../config.yaml') }}"
    - read_csv:
        path: "{{ nodes_csv_path | default('../nodes.csv') }}"
      register: nodes_csv_list
    - read_csv:
        path: "{{ networks_csv_path | default('../networks.csv') }}"
      register: networks_csv_list
    - read_csv:
        path: "{{ nodes_csv_path | default('../nodes.csv') }}"
        key: name
      register: nodes_csv_dict
    - read_csv:
        path: "{{ networks_csv_path | default('../networks.csv') }}"
        key: name
      register: networks_csv_dict

- name: Validate Config
  hosts: localhost
  connection: local
  tags: validate
  gather_facts: no
  tasks:
    - validate_config:
        servers: "{{ servers }}"
        networks: "{{ networks}}"
        role_used_network: "{{ role_used_network }}"
        vips: "{{ vips | default([]) }}"
      register: validate
    - debug:
        msg: "{{ validate.msg }}"

- name: Deploy Tasks
  hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: network
      vars:
        - network: "{{ item.name }}"
        - cidr: "{{ item.cidr }}"
      with_items: "{{ networks_csv_list.list }}"
      tags:
        - full-create-server
        - network-config

    - include_role:
        name: port
      vars:
        node_info: "{{ item }}"
      with_dict: "{{ networks_csv_dict.dict }}"
      tags:
        - full-create-server
        - network-config

    - include_role:
        name: nic_config
      vars:
        role: "{{ item.role }}"
        name: "{{ item.name }}"
      tags:
        - full-create-server
        - network-config
      with_items: "{{ nodes_csv_list.list }}"


    - include_role:
        name: server
      vars:
        server: "{{ item }}"
      with_items: "{{ nodes_csv_list.list }}"
      tags:
        - full-create-server
        - create-server

- name: Apply nic-config
  tags:
    - reconfig-network
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - fail:
        msg: "Reconfig network need host, use --hosts and --inventory"
      when: host is not defined
    - include_role:
        name: nic_config
      vars:
        role: "{{ item.role }}"
        name: "{{ item.name }}"
      tags:
        - reconfig-network
      with_inventory_hostname: "{{ host.split(',') | default('') }}"

- name: Apply nic-config
  tags:
    - reconfig-network
  become: true
  hosts: "{{ host | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Create folder
      file:
        state: directory
        dest: '/etc/os-net-config'

    - name: Copy nic config file
      copy:
        src: "{{ playbook_dir | dirname }}/kolla-servers/{{ inventory_hostname }}-config.yaml"
        dest: "/etc/os-net-config/config.yaml"
    - name: Copy mapping file
      copy:
        src: "{{ playbook_dir | dirname }}/kolla-servers/{{ inventory_hostname }}-mapping.yaml"
        dest: "/etc/os-net-config/mapping.yaml"
      ignore_errors: yes

    - name: Apply nic config with async
      command: os-net-config
      async: 180
      poll: 5

- name: Update /etc/hosts
  hosts: localhost
  connection: local
  tags: etc-hosts
  gather_facts: no
  vars:
    action: 'create'
  tasks:
    - include_role:
        name: etc_hosts


- name: Recreate inventory file
  hosts: localhost
  tags:
    - create-inventory
    - full-server-create
  connection: local
  gather_facts: no
  vars:
    action: 'create'
  tasks:
    - include_role:
        name: inventory

- name: Create with deployed node
  hosts: localhost
  tags: deployed-server
  connection: local
  gather_facts: no
  vars:
    action: 'create'
    use_undercloud: false
  tasks:
    - include_role:
        name: port
      with_items: "{{ config_reg.parsed_config }}"
    - include_role:
        name: nic_config
    - include_role:
        name: inventory


- name: Reconfig Network
  hosts: localhost
  connection: local
  tags:
    - reconfig-network
  tasks:

- name: Destory all
  hosts: localhost
  connection: local
  tags: destroy
  gather_facts: no
  vars:
    use_undercloud: true
  tasks:
    - include_role:
        name: server
    - include_role:
        name: port
    - include_role:
        name: network
    - include_role:
        name: etc_hosts
