---
- name: Read variables
  hosts: localhost
  connection: local
  tags: always
  gather_facts: no
  tasks:
    - include_vars: "{{ config_path | default('../config.yaml') }}"
    - read_csv:
        path: "{{ nodes_csv_path | default('../nodes.csv') }}"
      register: nodes_csv_list

    - read_csv:
        path: "{{ networks_csv_path | default('../networks.csv') }}"
      register: networks_csv_list

    - read_csv:
        path: "{{ nodes_csv_path | default('../nodes.csv') }}"
        key: name
      register: nodes_csv_dict

    - read_csv:
        path: "{{ networks_csv_path | default('../networks.csv') }}"
        key: name
      register: networks_csv_dict


- name: Full Create Server
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - full-create-server
  tasks:
    - include_role:
        name: network
      vars:
        - name: "{{ item.name }}"
        - cidr: "{{ item.cidr }}"
      with_items: "{{ networks_csv_list.list }}"

    - include_role:
        name: port
      vars:
        name: "{{ item.name }}"
        node_info: "{{ item }}"
      with_items: "{{ nodes_csv_list.list }}"

    - include_role:
        name: nic_config
      vars:
        copy_from_role: "{{ item.role }}"
        name: "{{ item.name }}"
      with_items: "{{ nodes_csv_list.list }}"


- name: Create Server
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - full-create-server
    - create-server
  tasks:
    - include_role:
        name: server
      vars:
        server: "{{ item }}"
      with_items: "{{ nodes_csv_list.list }}"


- name: Create with deployed node
  hosts: localhost
  tags: deployed-server
  connection: local
  gather_facts: no
  vars:
    deploy_action: 'create'
    use_undercloud: false
  tasks:
    - include_role:
        name: port
      vars:
        name: "{{ item.name }}"
        node_info: "{{ item }}"
      with_items: "{{ nodes_csv_list.list }}"


- name: Update network config
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - update-network-config
  tasks:
    - include_role:
        name: port
      vars:
        name: "{{ item.name }}"
        node_info: "{{ item }}"
      with_items: "{{ nodes_csv_list.list }}"

    - include_role:
        name: nic_config


- name: Update node nic config
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - reconfig-network
    - update-nic-config
  tasks:
    - include_role:
        name: nic_config


- name: Apply node nic config
  become: true
  hosts: "{{ host | default('all')}}"
  gather_facts: no
  tags:
    - reconfig-network
    - apply-nic-config
  tasks:
    - name: Create folder
      file:
        state: directory
        dest: '/etc/os-net-config'
    - name: Copy nic config file
      copy:
        src: "{{ playbook_dir | dirname }}/kolla-servers/{{ inventory_hostname }}-config.yaml"
        dest: "/etc/os-net-config/config.yaml"
    - name: Copy mapping file
      copy:
        src: "{{ playbook_dir | dirname }}/kolla-servers/{{ inventory_hostname }}-mapping.yaml"
        dest: "/etc/os-net-config/mapping.yaml"
      ignore_errors: yes
    - name: Apply nic config with async
      command: os-net-config
      async: 180
      poll: 5


- name: Create inventory file
  hosts: localhost
  tags:
    - create-inventory
    - full-create-server
  connection: local
  gather_facts: no
  tasks:
    - include_role:
        name: inventory


- name: Update /etc/hosts
  hosts: localhost
  connection: local
  tags: etc-hosts
  gather_facts: no
  vars:
    deploy_action: 'create'
  tasks:
    - include_role:
        name: etc_hosts


- name: Destory all
  hosts: localhost
  connection: local
  tags: destroy
  gather_facts: no
  vars:
    use_undercloud: true
  tasks:
    - include_role:
        name: server
    - include_role:
        name: port
    - include_role:
        name: network
    - include_role:
        name: etc_hosts
