---
- name: Read variables
  hosts: localhost
  connection: local
  tags: always
  gather_facts: no
  tasks:
    - include_vars: "{{ config_path | default('../config.yaml') }}"

- name: Validate Config
  hosts: localhost
  connection: local
  tags: validate
  gather_facts: no
  tasks:
    - validate_config:
        servers: "{{ servers }}"
        networks: "{{ networks}}"
        role_used_network: "{{ role_used_network }}"
        vips: "{{ vips | default([]) }}"
      register: validate
    - debug:
        msg: "{{ validate.msg }}"

- name: Parse Config
  hosts: localhost
  connection: local
  tags:
    - 'destroy'
    - 'create-server'
    - 'reconfig-network'
    - 'create-inventory'
    - 'deployed-server'
  gather_facts: no
  tasks:
    - parse_config:
        servers: "{{ servers }}"
        networks: "{{ networks }}"
        network_require: "{{ role_used_network }}"
      register: config_reg
    - debug: var=config_reg.parsed_config

- name: Destory all
  hosts: localhost
  connection: local
  tags: destroy
  gather_facts: no
  vars:
    action: 'destroy'
    use_undercloud: true
  tasks:
    - include_role:
        name: server
    - include_role:
        name: port
    - include_role:
        name: network
    - include_role:
        name: etc_hosts

- name: Create servers
  hosts: localhost
  connection: local
  tags: create-server
  gather_facts: no
  vars:
    action: 'create'
    use_undercloud: true
  tasks:
    - include_role:
        name: network

    - include_role:
        name: port
      with_items: "{{ config_reg.parsed_config }}"

    - include_role:
        name: nic_config
      with_items: "{{ config_reg.parsed_config }}"

    - include_role:
        name: server
      vars:
        server: "{{ item }}"
      with_items: "{{ config_reg.parsed_config }}"

    - include_role:
        name: inventory

- name: Update /etc/hosts
  hosts: localhost
  connection: local
  tags: etc-hosts
  gather_facts: no
  vars:
    action: 'create'
  tasks:
    - include_role:
        name: etc_hosts

- name: Recreate nic-config
  hosts: localhost
  connection: local
  tags: reconfig-network
  gather_facts: no
  vars:
    action: 'reconfig'
    use_undercloud: true
  tasks:
    - include_role:
        name: port
      with_items: "{{ config_reg.parsed_config }}"
    - include_role:
        name: nic_config
      with_items: "{{ config_reg.parsed_config }}"

- name: Apply nic-config
  tags: reconfig-network
  become: true
  hosts: "{{ host | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Create folder
      file:
        state: directory
        dest: '/etc/os-net-config'

    - name: Copy nic config file
      copy:
        src: "{{ playbook_dir | dirname }}/kolla-servers/{{ inventory_hostname }}-config.yaml"
        dest: "/etc/os-net-config/config.yaml"
    - name: Copy mapping file
      copy:
        src: "{{ playbook_dir | dirname }}/kolla-servers/{{ inventory_hostname }}-mapping.yaml"
        dest: "/etc/os-net-config/mapping.yaml"
      ignore_errors: yes

    - name: Apply nic config with async
      command: os-net-config
      async: 60
      poll: 5

- name: Recreate inventory file
  hosts: localhost
  tags: create-inventory
  connection: local
  gather_facts: no
  vars:
    action: 'create'
  tasks:
    - include_role:
        name: inventory

- name: Create with deployed node
  hosts: localhost
  tags: deployed-server
  connection: local
  gather_facts: no
  vars:
    action: 'create'
    use_undercloud: false
  tasks:
    - include_role:
        name: port
      with_items: "{{ config_reg.parsed_config }}"
    - include_role:
        name: nic_config
    - include_role:
        name: inventory
