network_config:
  - type: interface
    name: nic1
    use_dhcp: false
    addresses:
      - ip_netmask: ctlplane
  - type: linux_bond
    name: bond1
    bonding_options: bond_options
    members:
      - type: interface
        name: nic2
      - type: interface
        name: nic3
  - type: vlan
    vlan_id: storage_vlan_id
    device: bond1
    addresses:
      - ip_netmask: storage
  - type: vlan
    vlan_id: external_vlan_id
    device: bond1
    addresses:
      - ip_netmask: external
    routes:
      - default: true
        next_hop: default_gateway
  - type: vlan
    vlan_id: internal_vlan_id
    device: bond1
    addresses:
      - ip_netmask: internal
